name: CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10'

    - name: Install Dependencies
      run: yarn

    - name: Test lint and build
      run: |
        yarn test
        yarn lint
        yarn build

